version: "3.9"
services:
  mysql:
    image: mysql:8.0.32
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    env_file: mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ../conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../init-load-dir:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306
    restart: always

volumes:
  mysql_data:
